// <auto-generated />
namespace Visuals.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class VisualsFramework : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VisualsFramework));
        
        string IMigrationMetadata.Id
        {
            get { return "201306091845247_VisualsFramework"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
