//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visuals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Avatar { get; set; }
        public string User { get; set; }
        public string AvatarLink { get; set; }
        public string Message { get; set; }
        public int PostId { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
