//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visuals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Posts = new HashSet<Post>();
            this.Pics = new HashSet<Pic>();
            this.InterestingPics = new HashSet<Pic>();
        }
    
        public int Id { get; set; }
        public string Property1 { get; set; }
        public string MiniAvatar { get; set; }
        public string Link { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Pic> Pics { get; set; }
        public virtual ICollection<Pic> InterestingPics { get; set; }
    }
}
